# Generated by Django 4.0.5 on 2022-06-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=10000)),
                ('received_tags', models.CharField(max_length=100)),
            ],
        ),
    ]
